---
title: "MRMC Practice"
author: "남승찬"
date: '2022년 1월 25일 (화)'
output:
  html_document:
    theme: default
    highlight: textmate
    toc: TRUE
    toc_depth: 3  
    toc_float: TRUE
    number_sections: FALSE

  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(MRMCaov)
library(pROC)
head(VanDyke)
X <- VanDyke
```

<br>

## Reader Performance Metrics
### ROC Curve Metrics

```{r message=FALSE}
## Total area under the ROC curve
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE)
roc.info$auc
## Partial area for specificity from 0.7 to 1.0
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE,
partial.auc=c(0.7, 1), auc.polygon=TRUE, auc.polygon.col='#377eb822')
roc.info$auc
## Partial area for sensitivity from 0.7 to 1.0
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE,
partial.auc=c(1, 0.7), partial.auc.focus='sens', auc.polygon=TRUE, auc.polygon.col='#377eb822')
roc.info$auc
## Sensitivity for given specificity
coords(roc.info, 0.8, input='specificity')
## Specificity for given sensitivity
coords(roc.info, 0.8, input='sensitivity')
```

### Binary Metrics
```{r}
## Create binary classification
VanDyke$binary_rating <- VanDyke$rating >= 3
X <- VanDyke
## Sensitivity
table(real=X$truth, pred=X$binary_rating)
392/(58+392)
## Specificity
table(real=X$truth, pred=X$binary_rating)
585/(585+105)
```

<br>

## MRMC Analysis
### ROC Curve Metrics

```{r message=FALSE}
## 10가지 경우에 대한 AUC 비교
RESULT1 <- matrix(1:10, 10, 3)
RESULT1[,1] <- c(1,1,2,2,3,3,4,4,5,5)
RESULT1[,2] <- rep(1:2, 5)
colnames(RESULT1) <- c('Reader', 'Treatment', 'AUC')
par(mfrow=c(2,3)) ; par(pty="s")
for (i in 1:5) {
X1 <- X[X$reader == i, ]
X11 <- X1[X1$treatment == 1,]
X12 <- X1[X1$treatment == 2,]
ROC1 <- roc(X11$truth, X11$rating)
ROC2 <- roc(X12$truth, X12$rating)
RESULT1[i*2-1, 3] <- ROC1$auc
RESULT1[i*2, 3] <- ROC2$auc
}
RESULT1
```
<br><br>

```{r message=FALSE}
## Test (treatment) 별
RESULT2 <- matrix(c(1,2), 2, 2)
colnames(RESULT2) <- c('Treatment', 'AUC')
par(mfrow=c(1,2)) ; par(pty="s")
for (i in 1:2) {
X1 <- X[X$treatment == i,]
X11 <- X1[X1$reader == 1,]
X12 <- X1[X1$reader == 2,]
X13 <- X1[X1$reader == 3,]
X14 <- X1[X1$reader == 4,]
X15 <- X1[X1$reader == 5,]
MR <- (X11$rating + X12$rating + X13$rating + X14$rating + X15$rating)/5
ROC <- roc(X11$truth, MR)
plot.roc(ROC, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE, main=paste('Treatment',i))
RESULT2[i, 2] <- ROC$auc
}
RESULT2
```